# One-to-Many and Many-to-Many Joins - Lab

## Introduction

In this lab, you'll practice your knowledge on one-to-many and many-to-many relationships!

## Objectives

You will be able to:
- Query data using one-to-many and many-to-many joins
- Predict the resulting size of one-to-many and many-to-many joins

## One-to-Many and Many-to-Many Joins
<img src='images/Database-Schema.png' width="600">

## Connect to the Database

In [2]:
#Your code here
import sqlite3
conn = sqlite3.connect('data.sqlite')
c=conn.cursor()

## Employees and their Office (a One-to-One join)

Return a list of all of the employees with their first name, last name and the city and state of the office that they work out of (if they have one). Include all employees and order them by their first name, then their last name.

In [3]:
#Your code here
c.execute('''select employees.firstName, employees.lastName, offices.city, offices.state, offices.officeCode, employees.officeCode
from employees
join offices where employees.officeCode=offices.officeCode;''').fetchall()

[('Diane', 'Murphy', 'San Francisco', 'CA', '1', '1'),
 ('Mary', 'Patterson', 'San Francisco', 'CA', '1', '1'),
 ('Jeff', 'Firrelli', 'San Francisco', 'CA', '1', '1'),
 ('William', 'Patterson', 'Sydney', '', '6', '6'),
 ('Gerard', 'Bondur', 'Paris', '', '4', '4'),
 ('Anthony', 'Bow', 'San Francisco', 'CA', '1', '1'),
 ('Leslie', 'Jennings', 'San Francisco', 'CA', '1', '1'),
 ('Leslie', 'Thompson', 'San Francisco', 'CA', '1', '1'),
 ('Julie', 'Firrelli', 'Boston', 'MA', '2', '2'),
 ('Steve', 'Patterson', 'Boston', 'MA', '2', '2'),
 ('Foon Yue', 'Tseng', 'NYC', 'NY', '3', '3'),
 ('George', 'Vanauf', 'NYC', 'NY', '3', '3'),
 ('Loui', 'Bondur', 'Paris', '', '4', '4'),
 ('Gerard', 'Hernandez', 'Paris', '', '4', '4'),
 ('Pamela', 'Castillo', 'Paris', '', '4', '4'),
 ('Larry', 'Bott', 'London', '', '7', '7'),
 ('Barry', 'Jones', 'London', '', '7', '7'),
 ('Andy', 'Fixter', 'Sydney', '', '6', '6'),
 ('Peter', 'Marsh', 'Sydney', '', '6', '6'),
 ('Tom', 'King', 'Sydney', '', '6', '6'),
 ('Mami', 'Nishi', 'Tokyo', 'Chiyoda-Ku', '5', '5'),
 ('Yoshimi', 'Kato', 'Tokyo', 'Chiyoda-Ku', '5', '5'),
 ('Martin', 'Gerard', 'Paris', '', '4', '4')]

## Customers and their Orders (a One-to-Many join)

Return a list of all the customers first and last names along with a record for each of their order numbers, order dates and statuses.

In [4]:
# Your code here
c.execute('''select customers.contactFirstName, customers.contactLastName, orders.orderNumber, orders.orderDate, orders.status from customers join orders 
using(customerNumber);''').fetchall()

[('Carine ', 'Schmitt', '10123', '2003-05-20', 'Shipped'),
 ('Carine ', 'Schmitt', '10298', '2004-09-27', 'Shipped'),
 ('Carine ', 'Schmitt', '10345', '2004-11-25', 'Shipped'),
 ('Jean', 'King', '10124', '2003-05-21', 'Shipped'),
 ('Jean', 'King', '10278', '2004-08-06', 'Shipped'),
 ('Jean', 'King', '10346', '2004-11-29', 'Shipped'),
 ('Peter', 'Ferguson', '10120', '2003-04-29', 'Shipped'),
 ('Peter', 'Ferguson', '10125', '2003-05-21', 'Shipped'),
 ('Peter', 'Ferguson', '10223', '2004-02-20', 'Shipped'),
 ('Peter', 'Ferguson', '10342', '2004-11-24', 'Shipped'),
 ('Peter', 'Ferguson', '10347', '2004-11-29', 'Shipped'),
 ('Janine ', 'Labrune', '10275', '2004-07-23', 'Shipped'),
 ('Janine ', 'Labrune', '10315', '2004-10-29', 'Shipped'),
 ('Janine ', 'Labrune', '10375', '2005-02-03', 'Shipped'),
 ('Janine ', 'Labrune', '10425', '2005-05-31', 'In Process'),
 ('Jonas ', 'Bergulfsen', '10103', '2003-01-29', 'Shipped'),
 ('Jonas ', 'Bergulfsen', '10158', '2003-10-10', 'Shipped'),
 ('Jonas ', 'Bergulfsen', '10309', '2004-10-15', 'Shipped'),
 ('Jonas ', 'Bergulfsen', '10325', '2004-11-05', 'Shipped'),
 ('Susan', 'Nelson', '10113', '2003-03-26', 'Shipped'),
 ('Susan', 'Nelson', '10135', '2003-07-02', 'Shipped'),
 ('Susan', 'Nelson', '10142', '2003-08-08', 'Shipped'),
 ('Susan', 'Nelson', '10182', '2003-11-12', 'Shipped'),
 ('Susan', 'Nelson', '10229', '2004-03-11', 'Shipped'),
 ('Susan', 'Nelson', '10271', '2004-07-20', 'Shipped'),
 ('Susan', 'Nelson', '10282', '2004-08-20', 'Shipped'),
 ('Susan', 'Nelson', '10312', '2004-10-21', 'Shipped'),
 ('Susan', 'Nelson', '10335', '2004-11-19', 'Shipped'),
 ('Susan', 'Nelson', '10357', '2004-12-10', 'Shipped'),
 ('Susan', 'Nelson', '10368', '2005-01-19', 'Shipped'),
 ('Susan', 'Nelson', '10371', '2005-01-23', 'Shipped'),
 ('Susan', 'Nelson', '10382', '2005-02-17', 'Shipped'),
 ('Susan', 'Nelson', '10385', '2005-02-28', 'Shipped'),
 ('Susan', 'Nelson', '10390', '2005-03-04', 'Shipped'),
 ('Susan', 'Nelson', '10396', '2005-03-23', 'Shipped'),
 ('Susan', 'Nelson', '10421', '2005-05-29', 'In Process'),
 ('Roland', 'Keitel', '10101', '2003-01-09', 'Shipped'),
 ('Roland', 'Keitel', '10230', '2004-03-15', 'Shipped'),
 ('Roland', 'Keitel', '10300', '2003-10-04', 'Shipped'),
 ('Roland', 'Keitel', '10323', '2004-11-05', 'Shipped'),
 ('Julie', 'Murphy', '10111', '2003-03-25', 'Shipped'),
 ('Julie', 'Murphy', '10201', '2003-12-01', 'Shipped'),
 ('Julie', 'Murphy', '10333', '2004-11-18', 'Shipped'),
 ('Kwai', 'Lee', '10107', '2003-02-24', 'Shipped'),
 ('Kwai', 'Lee', '10248', '2004-05-07', 'Cancelled'),
 ('Kwai', 'Lee', '10292', '2004-09-08', 'Shipped'),
 ('Kwai', 'Lee', '10329', '2004-11-15', 'Shipped'),
 ('Diego ', 'Freyre', '10104', '2003-01-31', 'Shipped'),
 ('Diego ', 'Freyre', '10128', '2003-06-06', 'Shipped'),
 ('Diego ', 'Freyre', '10133', '2003-06-27', 'Shipped'),
 ('Diego ', 'Freyre', '10153', '2003-09-28', 'Shipped'),
 ('Diego ', 'Freyre', '10156', '2003-10-08', 'Shipped'),
 ('Diego ', 'Freyre', '10190', '2003-11-19', 'Shipped'),
 ('Diego ', 'Freyre', '10203', '2003-12-02', 'Shipped'),
 ('Diego ', 'Freyre', '10205', '2003-12-03', 'Shipped'),
 ('Diego ', 'Freyre', '10212', '2004-01-16', 'Shipped'),
 ('Diego ', 'Freyre', '10244', '2004-04-29', 'Shipped'),
 ('Diego ', 'Freyre', '10246', '2004-05-05', 'Shipped'),
 ('Diego ', 'Freyre', '10262', '2004-06-24', 'Cancelled'),
 ('Diego ', 'Freyre', '10279', '2004-08-09', 'Shipped'),
 ('Diego ', 'Freyre', '10311', '2004-10-16', 'Shipped'),
 ('Diego ', 'Freyre', '10350', '2004-12-02', 'Shipped'),
 ('Diego ', 'Freyre', '10355', '2004-12-07', 'Shipped'),
 ('Diego ', 'Freyre', '10358', '2004-12-10', 'Shipped'),
 ('Diego ', 'Freyre', '10378', '2005-02-10', 'Shipped'),
 ('Diego ', 'Freyre', '10379', '2005-02-10', 'Shipped'),
 ('Diego ', 'Freyre', '10380', '2005-02-16', 'Shipped'),
 ('Diego ', 'Freyre', '10383', '2005-02-22', 'Shipped'),
 ('Diego ', 'Freyre', '10386', '2005-03-01', 'Resolved'),
 ('Diego ', 'Freyre', '10394', '2005-03-15', 'Shipped'),
 ('Diego ', 'Freyre', '10412', '2005-05-03', 'Shipped'),
 ('Diego ', 'Freyre', '10417', '2005-05-13', 'Disputed'),
 ('Diego ', 'Freyre', '10424', '2005-05-31', 'In Process'),
 ('Christina ', 'Berglund', '10112', '2003-03-24', 'Shipped'),
 ('Christina ', 'Berglund', '10320', '2004-11-03', 'Shipped'),
 ('Christina ', 'Berglund', '10326', '2004-11-09', 'Shipped'),
 ('Christina ', 'Berglund', '10334', '2004-11-19', 'On Hold'),
 ('Jytte ', 'Petersen', '10105', '2003-02-11', 'Shipped'),
 ('Jytte ', 'Petersen', '10238', '2004-04-09', 'Shipped'),
 ('Jytte ', 'Petersen', '10256', '2004-06-08', 'Shipped'),
 ('Jytte ', 'Petersen', '10327', '2004-11-10', 'Resolved'),
 ('Jytte ', 'Petersen', '10406', '2005-04-15', 'Disputed'),
 ('Mary ', 'Saveley', '10194', '2003-11-25', 'Shipped'),
 ('Mary ', 'Saveley', '10208', '2004-01-02', 'Shipped'),
 ('Mary ', 'Saveley', '10227', '2004-03-02', 'Shipped'),
 ('Eric', 'Natividad', '10117', '2003-04-16', 'Shipped'),
 ('Eric', 'Natividad', '10150', '2003-09-19', 'Shipped'),
 ('Eric', 'Natividad', '10165', '2003-10-22', 'Shipped'),
 ('Eric', 'Natividad', '10277', '2004-08-04', 'Shipped'),
 ('Eric', 'Natividad', '10387', '2005-03-02', 'Shipped'),
 ('Jeff', 'Young', '10127', '2003-06-03', 'Shipped'),
 ('Jeff', 'Young', '10204', '2003-12-02', 'Shipped'),
 ('Jeff', 'Young', '10267', '2004-07-07', 'Shipped'),
 ('Jeff', 'Young', '10349', '2004-12-01', 'Shipped'),
 ('Kelvin', 'Leong', '10272', '2004-07-20', 'Shipped'),
 ('Kelvin', 'Leong', '10281', '2004-08-19', 'Shipped'),
 ('Kelvin', 'Leong', '10318', '2004-11-02', 'Shipped'),
 ('Kelvin', 'Leong', '10422', '2005-05-30', 'In Process'),
 ('Juri', 'Hashimoto', '10140', '2003-07-24', 'Shipped'),
 ('Juri', 'Hashimoto', '10168', '2003-10-28', 'Shipped'),
 ('Juri', 'Hashimoto', '10317', '2004-11-02', 'Shipped'),
 ('Juri', 'Hashimoto', '10362', '2005-01-05', 'Shipped'),
 ('Wendy', 'Victorino', '10217', '2004-02-04', 'Shipped'),
 ('Wendy', 'Victorino', '10259', '2004-06-15', 'Shipped'),
 ('Wendy', 'Victorino', '10288', '2004-09-01', 'Shipped'),
 ('Wendy', 'Victorino', '10409', '2005-04-23', 'Shipped'),
 ('Veysel', 'Oeztan', '10181', '2003-11-12', 'Shipped'),
 ('Veysel', 'Oeztan', '10188', '2003-11-18', 'Shipped'),
 ('Veysel', 'Oeztan', '10289', '2004-09-03', 'Shipped'),
 ('Martine ', 'Rancé', '10180', '2003-11-11', 'Shipped'),
 ('Martine ', 'Rancé', '10224', '2004-02-21', 'Shipped'),
 ('Marie', 'Bertrand', '10114', '2003-04-01', 'Shipped'),
 ('Marie', 'Bertrand', '10286', '2004-08-28', 'Shipped'),
 ('Marie', 'Bertrand', '10336', '2004-11-20', 'Shipped'),
 ('Jerry', 'Tseng', '10228', '2004-03-10', 'Shipped'),
 ('Jerry', 'Tseng', '10249', '2004-05-08', 'Shipped'),
 ('Julie', 'King', '10172', '2003-11-05', 'Shipped'),
 ('Julie', 'King', '10263', '2004-06-28', 'Shipped'),
 ('Julie', 'King', '10413', '2005-05-05', 'Shipped'),
 ('Mory', 'Kentary', '10210', '2004-01-12', 'Shipped'),
 ('Mory', 'Kentary', '10240', '2004-04-13', 'Shipped'),
 ('Michael', 'Frick', '10102', '2003-01-10', 'Shipped'),
 ('Michael', 'Frick', '10237', '2004-04-05', 'Shipped'),
 ('Michael', 'Frick', '10324', '2004-11-05', 'Shipped'),
 ('Matti', 'Karttunen', '10155', '2003-10-06', 'Shipped'),
 ('Matti', 'Karttunen', '10299', '2004-09-30', 'Shipped'),
 ('Matti', 'Karttunen', '10377', '2005-02-09', 'Shipped'),
 ('Rachel', 'Ashworth', '10110', '2003-03-18', 'Shipped'),
 ('Rachel', 'Ashworth', '10306', '2004-10-14', 'Shipped'),
 ('Rachel', 'Ashworth', '10332', '2004-11-17', 'Shipped'),
 ('Dean', 'Cassidy', '10220', '2004-02-12', 'Shipped'),
 ('Dean', 'Cassidy', '10297', '2004-09-16', 'Shipped'),
 ('Leslie', 'Taylor', '10130', '2003-06-16', 'Shipped'),
 ('Leslie', 'Taylor', '10290', '2004-09-07', 'Shipped'),
 ('Leslie', 'Taylor', '10352', '2004-12-03', 'Shipped'),
 ('Elizabeth', 'Devon', '10253', '2004-06-01', 'Cancelled'),
 ('Elizabeth', 'Devon', '10302', '2003-10-06', 'Shipped'),
 ('Elizabeth', 'Devon', '10403', '2005-04-08', 'Shipped'),
 ('Yoshi ', 'Tamuri', '10206', '2003-12-05', 'Shipped'),
 ('Yoshi ', 'Tamuri', '10313', '2004-10-22', 'Shipped'),
 ('Miguel', 'Barajas', '10276', '2004-08-02', 'Shipped'),
 ('Miguel', 'Barajas', '10294', '2004-09-10', 'Shipped'),
 ('Julie', 'Young', '10145', '2003-08-25', 'Shipped'),
 ('Julie', 'Young', '10189', '2003-11-18', 'Shipped'),
 ('Julie', 'Young', '10367', '2005-01-12', 'Resolved'),
 ('Frédérique ', 'Citeaux', '10241', '2004-04-13', 'Shipped'),
 ('Frédérique ', 'Citeaux', '10255', '2004-06-04', 'Shipped'),
 ('Frédérique ', 'Citeaux', '10405', '2005-04-14', 'Shipped'),
 ('Mike', 'Gao', '10187', '2003-11-15', 'Shipped'),
 ('Mike', 'Gao', '10200', '2003-12-01', 'Shipped'),
 ('Eduardo ', 'Saavedra', '10118', '2003-04-21', 'Shipped'),
 ('Eduardo ', 'Saavedra', '10197', '2003-11-26', 'Shipped'),
 ('Eduardo ', 'Saavedra', '10340', '2004-11-24', 'Shipped'),
 ('Mary', 'Young', '10154', '2003-10-02', 'Shipped'),
 ('Mary', 'Young', '10376', '2005-02-08', 'Shipped'),
 ('Palle', 'Ibsen', '10161', '2003-10-17', 'Shipped'),
 ('Palle', 'Ibsen', '10314', '2004-10-22', 'Shipped'),
 ('Jean ', 'Fresnière', '10171', '2003-11-05', 'Shipped'),
 ('Jean ', 'Fresnière', '10261', '2004-06-17', 'Shipped'),
 ('Jean ', 'Fresnière', '10411', '2005-05-01', 'Shipped'),
 ('Valarie', 'Thompson', '10222', '2004-02-19', 'Shipped'),
 ('Valarie', 'Thompson', '10226', '2004-02-26', 'Shipped'),
 ('Helen ', 'Bennett', '10232', '2004-03-20', 'Shipped'),
 ('Helen ', 'Bennett', '10316', '2004-11-01', 'Shipped'),
 ('Annette ', 'Roulet', '10136', '2003-07-04', 'Shipped'),
 ('Annette ', 'Roulet', '10178', '2003-11-08', 'Shipped'),
 ('Annette ', 'Roulet', '10397', '2005-03-28', 'Shipped'),
 ('Paolo ', 'Accorti', '10280', '2004-08-17', 'Shipped'),
 ('Paolo ', 'Accorti', '10293', '2004-09-09', 'Shipped'),
 ('Daniel', 'Da Silva', '10134', '2003-07-01', 'Shipped'),
 ('Daniel', 'Da Silva', '10356', '2004-12-09', 'Shipped'),
 ('Daniel', 'Da Silva', '10395', '2005-03-17', 'Shipped'),
 ('Daniel ', 'Tonini', '10216', '2004-02-02', 'Shipped'),
 ('Daniel ', 'Tonini', '10304', '2004-10-11', 'Shipped'),
 ('Henriette ', 'Pfalzheim', '10191', '2003-11-20', 'Shipped'),
 ('Henriette ', 'Pfalzheim', '10310', '2004-10-16', 'Shipped'),
 ('Elizabeth ', 'Lincoln', '10235', '2004-04-02', 'Shipped'),
 ('Elizabeth ', 'Lincoln', '10283', '2004-08-20', 'Shipped'),
 ('Anna', "O'Hara", '10148', '2003-09-11', 'Shipped'),
 ('Anna', "O'Hara", '10169', '2003-11-04', 'Shipped'),
 ('Anna', "O'Hara", '10370', '2005-01-20', 'Shipped'),
 ('Anna', "O'Hara", '10391', '2005-03-09', 'Shipped'),
 ('Giovanni ', 'Rovelli', '10106', '2003-02-17', 'Shipped'),
 ('Giovanni ', 'Rovelli', '10173', '2003-11-05', 'Shipped'),
 ('Giovanni ', 'Rovelli', '10328', '2004-11-12', 'Shipped'),
 ('Adrian', 'Huxley', '10139', '2003-07-16', 'Shipped'),
 ('Adrian', 'Huxley', '10270', '2004-07-19', 'Shipped'),
 ('Adrian', 'Huxley', '10361', '2004-12-17', 'Shipped'),
 ('Adrian', 'Huxley', '10420', '2005-05-29', 'In Process'),
 ('Marta', 'Hernandez', '10285', '2004-08-27', 'Shipped'),
 ('Marta', 'Hernandez', '10305', '2004-10-13', 'Shipped'),
 ('Mihael', 'Holz', '10225', '2004-02-22', 'Shipped'),
 ('Mihael', 'Holz', '10287', '2004-08-30', 'Shipped'),
 ('Jan', 'Klaeboe', '10284', '2004-08-21', 'Shipped'),
 ('Jan', 'Klaeboe', '10301', '2003-10-05', 'Shipped'),
 ('Pirkko', 'Koskitalo', '10151', '2003-09-21', 'Shipped'),
 ('Pirkko', 'Koskitalo', '10239', '2004-04-12', 'Shipped'),
 ('Pirkko', 'Koskitalo', '10373', '2005-01-31', 'Shipped'),
 ('Catherine ', 'Dewey', '10221', '2004-02-18', 'Shipped'),
 ('Catherine ', 'Dewey', '10273', '2004-07-21', 'Shipped'),
 ('Catherine ', 'Dewey', '10423', '2005-05-30', 'In Process'),
 ('Steve', 'Frick', '10195', '2003-11-25', 'Shipped'),
 ('Steve', 'Frick', '10308', '2004-10-15', 'Shipped'),
 ('Wing', 'Huang', '10143', '2003-08-10', 'Shipped'),
 ('Wing', 'Huang', '10185', '2003-11-14', 'Shipped'),
 ('Wing', 'Huang', '10365', '2005-01-07', 'Shipped'),
 ('Julie', 'Brown', '10159', '2003-10-10', 'Shipped'),
 ('Julie', 'Brown', '10162', '2003-10-18', 'Shipped'),
 ('Julie', 'Brown', '10381', '2005-02-17', 'Shipped'),
 ('Julie', 'Brown', '10384', '2005-02-23', 'Shipped'),
 ('Mike', 'Graham', '10132', '2003-06-25', 'Shipped'),
 ('Mike', 'Graham', '10254', '2004-06-03', 'Shipped'),
 ('Mike', 'Graham', '10354', '2004-12-04', 'Shipped'),
 ('Mike', 'Graham', '10393', '2005-03-11', 'Shipped'),
 ('Mike', 'Graham', '10404', '2005-04-08', 'Shipped'),
 ('Ann ', 'Brown', '10129', '2003-06-12', 'Shipped'),
 ('Ann ', 'Brown', '10175', '2003-11-06', 'Shipped'),
 ('Ann ', 'Brown', '10351', '2004-12-03', 'Shipped'),
 ('William', 'Brown', '10233', '2004-03-29', 'Shipped'),
 ('William', 'Brown', '10251', '2004-05-18', 'Shipped'),
 ('William', 'Brown', '10401', '2005-04-03', 'On Hold'),
 ('Ben', 'Calaghan', '10152', '2003-09-25', 'Shipped'),
 ('Ben', 'Calaghan', '10174', '2003-11-06', 'Shipped'),
 ('Ben', 'Calaghan', '10374', '2005-02-02', 'Shipped'),
 ('Kalle', 'Suominen', '10141', '2003-08-01', 'Shipped'),
 ('Kalle', 'Suominen', '10247', '2004-05-05', 'Shipped'),
 ('Kalle', 'Suominen', '10363', '2005-01-06', 'Shipped'),
 ('Francisca', 'Cervantes', '10183', '2003-11-13', 'Shipped'),
 ('Francisca', 'Cervantes', '10307', '2004-10-14', 'Shipped'),
 ('Jesus', 'Fernandez', '10177', '2003-11-07', 'Shipped'),
 ('Jesus', 'Fernandez', '10231', '2004-03-19', 'Shipped'),
 ('Brian', 'Chandler', '10160', '2003-10-11', 'Shipped'),
 ('Brian', 'Chandler', '10209', '2004-01-09', 'Shipped'),
 ('Laurence ', 'Lebihan', '10122', '2003-05-08', 'Shipped'),
 ('Laurence ', 'Lebihan', '10344', '2004-11-25', 'Shipped'),
 ('Laurence ', 'Lebihan', '10364', '2005-01-06', 'Shipped'),
 ('Paul ', 'Henriot', '10121', '2003-05-07', 'Shipped'),
 ('Paul ', 'Henriot', '10137', '2003-07-10', 'Shipped'),
 ('Paul ', 'Henriot', '10343', '2004-11-24', 'Shipped'),
 ('Paul ', 'Henriot', '10359', '2004-12-15', 'Shipped'),
 ('Paul ', 'Henriot', '10398', '2005-03-30', 'Shipped'),
 ('Wales', 'MacKinlay', '10202', '2003-12-02', 'Shipped'),
 ('Wales', 'MacKinlay', '10260', '2004-06-16', 'Cancelled'),
 ('Wales', 'MacKinlay', '10410', '2005-04-29', 'Shipped'),
 ('Juri', 'Yoshido', '10264', '2004-06-30', 'Shipped'),
 ('Juri', 'Yoshido', '10295', '2004-09-10', 'Shipped'),
 ('Juri', 'Yoshido', '10414', '2005-05-06', 'On Hold'),
 ('Dorothy', 'Young', '10100', '2003-01-06', 'Shipped'),
 ('Dorothy', 'Young', '10192', '2003-11-20', 'Shipped'),
 ('Dorothy', 'Young', '10322', '2004-11-04', 'Shipped'),
 ('Allen', 'Nelson', '10147', '2003-09-05', 'Shipped'),
 ('Allen', 'Nelson', '10274', '2004-07-21', 'Shipped'),
 ('Allen', 'Nelson', '10369', '2005-01-20', 'Shipped'),
 ('Pascale ', 'Cartrain', '10116', '2003-04-11', 'Shipped'),
 ('Pascale ', 'Cartrain', '10144', '2003-08-13', 'Shipped'),
 ('Pascale ', 'Cartrain', '10338', '2004-11-22', 'Shipped'),
 ('Pascale ', 'Cartrain', '10366', '2005-01-10', 'Shipped'),
 ('Georg ', 'Pipps', '10119', '2003-04-28', 'Shipped'),
 ('Georg ', 'Pipps', '10269', '2004-07-16', 'Shipped'),
 ('Georg ', 'Pipps', '10341', '2004-11-24', 'Shipped'),
 ('Georg ', 'Pipps', '10419', '2005-05-17', 'Shipped'),
 ('Arnold', 'Cruz', '10108', '2003-03-03', 'Shipped'),
 ('Arnold', 'Cruz', '10198', '2003-11-27', 'Shipped'),
 ('Arnold', 'Cruz', '10330', '2004-11-16', 'Shipped'),
 ('Maurizio ', 'Moroni', '10176', '2003-11-06', 'Shipped'),
 ('Maurizio ', 'Moroni', '10266', '2004-07-06', 'Shipped'),
 ('Maurizio ', 'Moroni', '10416', '2005-05-10', 'Shipped'),
 ('Akiko', 'Shimamura', '10258', '2004-06-15', 'Shipped'),
 ('Akiko', 'Shimamura', '10339', '2004-11-23', 'Shipped'),
 ('Akiko', 'Shimamura', '10372', '2005-01-26', 'Shipped'),
 ('Akiko', 'Shimamura', '10408', '2005-04-22', 'Shipped'),
 ('Dominique', 'Perrier', '10211', '2004-01-15', 'Shipped'),
 ('Dominique', 'Perrier', '10252', '2004-05-26', 'Shipped'),
 ('Dominique', 'Perrier', '10402', '2005-04-07', 'Shipped'),
 ('Sarah', 'McRoy', '10234', '2004-03-30', 'Shipped'),
 ('Sarah', 'McRoy', '10268', '2004-07-12', 'Shipped'),
 ('Sarah', 'McRoy', '10418', '2005-05-16', 'Shipped'),
 ('Michael', 'Donnermeyer', '10296', '2004-09-15', 'Shipped'),
 ('Maria', 'Hernandez', '10115', '2003-04-04', 'Shipped'),
 ('Maria', 'Hernandez', '10163', '2003-10-20', 'Shipped'),
 ('Maria', 'Hernandez', '10337', '2004-11-21', 'Shipped'),
 ('Dan', 'Lewis', '10131', '2003-06-16', 'Shipped'),
 ('Dan', 'Lewis', '10146', '2003-09-03', 'Shipped'),
 ('Dan', 'Lewis', '10353', '2004-12-04', 'Shipped'),
 ('Martha', 'Larsson', '10167', '2003-10-23', 'Cancelled'),
 ('Martha', 'Larsson', '10291', '2004-09-08', 'Shipped'),
 ('Martha', 'Larsson', '10389', '2005-03-03', 'Shipped'),
 ('Sue', 'Frick', '10250', '2004-05-11', 'Shipped'),
 ('Sue', 'Frick', '10257', '2004-06-14', 'Shipped'),
 ('Sue', 'Frick', '10400', '2005-04-01', 'Shipped'),
 ('Sue', 'Frick', '10407', '2005-04-22', 'On Hold'),
 ('Roland ', 'Mendel', '10164', '2003-10-21', 'Resolved'),
 ('Roland ', 'Mendel', '10170', '2003-11-04', 'Shipped'),
 ('Roland ', 'Mendel', '10392', '2005-03-10', 'Shipped'),
 ('Leslie', 'Murphy', '10196', '2003-11-26', 'Shipped'),
 ('Leslie', 'Murphy', '10245', '2004-05-04', 'Shipped'),
 ('Yu', 'Choi', '10242', '2004-04-20', 'Shipped'),
 ('Yu', 'Choi', '10319', '2004-11-03', 'Shipped'),
 ('Martín ', 'Sommer', '10126', '2003-05-28', 'Shipped'),
 ('Martín ', 'Sommer', '10214', '2004-01-26', 'Shipped'),
 ('Martín ', 'Sommer', '10348', '2004-11-01', 'Shipped'),
 ('Violeta', 'Benitez', '10166', '2003-10-21', 'Shipped'),
 ('Violeta', 'Benitez', '10321', '2004-11-04', 'Shipped'),
 ('Violeta', 'Benitez', '10388', '2005-03-03', 'Shipped'),
 ('Sean', 'Clenahan', '10193', '2003-11-21', 'Shipped'),
 ('Sean', 'Clenahan', '10265', '2004-07-02', 'Shipped'),
 ('Sean', 'Clenahan', '10415', '2005-05-09', 'Disputed'),
 ('Franco', 'Ricotti', '10157', '2003-10-09', 'Shipped'),
 ('Franco', 'Ricotti', '10218', '2004-02-09', 'Shipped'),
 ('Steve', 'Thompson', '10199', '2003-12-01', 'Shipped'),
 ('Steve', 'Thompson', '10215', '2004-01-29', 'Shipped'),
 ('José Pedro ', 'Roel', '10184', '2003-11-14', 'Shipped'),
 ('José Pedro ', 'Roel', '10303', '2004-10-06', 'Shipped'),
 ('Rosa', 'Salazar', '10109', '2003-03-10', 'Shipped'),
 ('Rosa', 'Salazar', '10236', '2004-04-03', 'Shipped'),
 ('Rosa', 'Salazar', '10331', '2004-11-17', 'Shipped'),
 ('Sue', 'Taylor', '10149', '2003-09-12', 'Shipped'),
 ('Sue', 'Taylor', '10219', '2004-02-10', 'Shipped'),
 ('Thomas ', 'Smith', '10186', '2003-11-14', 'Shipped'),
 ('Thomas ', 'Smith', '10213', '2004-01-22', 'Shipped'),
 ('Valarie', 'Franco', '10207', '2003-12-09', 'Shipped'),
 ('Valarie', 'Franco', '10243', '2004-04-26', 'Shipped'),
 ('Tony', 'Snowden', '10138', '2003-07-07', 'Shipped'),
 ('Tony', 'Snowden', '10179', '2003-11-11', 'Cancelled'),
 ('Tony', 'Snowden', '10360', '2004-12-16', 'Shipped'),
 ('Tony', 'Snowden', '10399', '2005-04-01', 'Shipped')]

## Customers and their Payments (another One-to-Many join)

Return a list of customers first and last names along with details about their payments including the amount and date of payments. Sort these results in descending order by the payment amount.

In [7]:
# Your code here
c.execute('''select customers.contactFirstName, customers.contactLastName, 
orders.orderDate, orderdetails.priceEach from customers
inner join orders using(customerNumber)
inner join orderdetails using(orderNumber);''').fetchall()

[('Carine ', 'Schmitt', '2003-05-20', '114.84'),
 ('Carine ', 'Schmitt', '2003-05-20', '117.26'),
 ('Carine ', 'Schmitt', '2003-05-20', '120.71'),
 ('Carine ', 'Schmitt', '2003-05-20', '43.27'),
 ('Carine ', 'Schmitt', '2004-09-27', '105.86'),
 ('Carine ', 'Schmitt', '2004-09-27', '60.57'),
 ('Carine ', 'Schmitt', '2004-11-25', '38.98'),
 ('Jean', 'King', '2003-05-21', '101.73'),
 ('Jean', 'King', '2003-05-21', '111.87'),
 ('Jean', 'King', '2003-05-21', '153.00'),
 ('Jean', 'King', '2003-05-21', '30.53'),
 ('Jean', 'King', '2003-05-21', '36.11'),
 ('Jean', 'King', '2003-05-21', '36.29'),
 ('Jean', 'King', '2003-05-21', '58.12'),
 ('Jean', 'King', '2003-05-21', '62.47'),
 ('Jean', 'King', '2003-05-21', '66.28'),
 ('Jean', 'King', '2003-05-21', '74.51'),
 ('Jean', 'King', '2003-05-21', '75.46'),
 ('Jean', 'King', '2003-05-21', '76.19'),
 ('Jean', 'King', '2003-05-21', '93.95'),
 ('Jean', 'King', '2004-08-06', '107.02'),
 ('Jean', 'King', '2004-08-06', '114.44'),
 ('Jean', 'King', '2004-08-06', '114.65'),
 ('Jean', 'King', '2004-08-06', '117.48'),
 ('Jean', 'King', '2004-08-06', '118.07'),
 ('Jean', 'King', '2004-08-06', '136.22'),
 ('Jean', 'King', '2004-08-06', '167.65'),
 ('Jean', 'King', '2004-08-06', '37.38'),
 ('Jean', 'King', '2004-08-06', '48.80'),
 ('Jean', 'King', '2004-08-06', '73.15'),
 ('Jean', 'King', '2004-11-29', '103.87'),
 ('Jean', 'King', '2004-11-29', '117.44'),
 ('Jean', 'King', '2004-11-29', '38.57'),
 ('Jean', 'King', '2004-11-29', '80.47'),
 ('Jean', 'King', '2004-11-29', '87.24'),
 ('Jean', 'King', '2004-11-29', '88.36'),
 ('Peter', 'Ferguson', '2003-04-29', '106.79'),
 ('Peter', 'Ferguson', '2003-04-29', '110.45'),
 ('Peter', 'Ferguson', '2003-04-29', '118.94'),
 ('Peter', 'Ferguson', '2003-04-29', '158.80'),
 ('Peter', 'Ferguson', '2003-04-29', '41.46'),
 ('Peter', 'Ferguson', '2003-04-29', '57.54'),
 ('Peter', 'Ferguson', '2003-04-29', '68.79'),
 ('Peter', 'Ferguson', '2003-04-29', '71.73'),
 ('Peter', 'Ferguson', '2003-04-29', '72.00'),
 ('Peter', 'Ferguson', '2003-04-29', '72.36'),
 ('Peter', 'Ferguson', '2003-04-29', '81.77'),
 ('Peter', 'Ferguson', '2003-04-29', '82.79'),
 ('Peter', 'Ferguson', '2003-04-29', '91.34'),
 ('Peter', 'Ferguson', '2003-04-29', '93.01'),
 ('Peter', 'Ferguson', '2003-04-29', '94.90'),
 ('Peter', 'Ferguson', '2003-05-21', '138.38'),
 ('Peter', 'Ferguson', '2003-05-21', '89.38'),
 ('Peter', 'Ferguson', '2004-02-20', '104.81'),
 ('Peter', 'Ferguson', '2004-02-20', '110.61'),
 ('Peter', 'Ferguson', '2004-02-20', '113.90'),
 ('Peter', 'Ferguson', '2004-02-20', '189.79'),
 ('Peter', 'Ferguson', '2004-02-20', '41.02'),
 ('Peter', 'Ferguson', '2004-02-20', '58.75'),
 ('Peter', 'Ferguson', '2004-02-20', '60.94'),
 ('Peter', 'Ferguson', '2004-02-20', '66.73'),
 ('Peter', 'Ferguson', '2004-02-20', '67.58'),
 ('Peter', 'Ferguson', '2004-02-20', '68.10'),
 ('Peter', 'Ferguson', '2004-02-20', '79.20'),
 ('Peter', 'Ferguson', '2004-02-20', '80.39'),
 ('Peter', 'Ferguson', '2004-02-20', '84.03'),
 ('Peter', 'Ferguson', '2004-02-20', '87.54'),
 ('Peter', 'Ferguson', '2004-02-20', '90.90'),
 ('Peter', 'Ferguson', '2004-11-24', '112.34'),
 ('Peter', 'Ferguson', '2004-11-24', '115.22'),
 ('Peter', 'Ferguson', '2004-11-24', '118.89'),
 ('Peter', 'Ferguson', '2004-11-24', '124.99'),
 ('Peter', 'Ferguson', '2004-11-24', '136.70'),
 ('Peter', 'Ferguson', '2004-11-24', '167.65'),
 ('Peter', 'Ferguson', '2004-11-24', '30.59'),
 ('Peter', 'Ferguson', '2004-11-24', '57.82'),
 ('Peter', 'Ferguson', '2004-11-24', '60.01'),
 ('Peter', 'Ferguson', '2004-11-24', '63.14'),
 ('Peter', 'Ferguson', '2004-11-24', '76.39'),
 ('Peter', 'Ferguson', '2004-11-29', '113.17'),
 ('Peter', 'Ferguson', '2004-11-29', '115.03'),
 ('Peter', 'Ferguson', '2004-11-29', '132.57'),
 ('Peter', 'Ferguson', '2004-11-29', '132.97'),
 ('Peter', 'Ferguson', '2004-11-29', '136.69'),
 ('Peter', 'Ferguson', '2004-11-29', '188.58'),
 ('Peter', 'Ferguson', '2004-11-29', '46.36'),
 ('Peter', 'Ferguson', '2004-11-29', '51.05'),
 ('Peter', 'Ferguson', '2004-11-29', '60.59'),
 ('Peter', 'Ferguson', '2004-11-29', '84.09'),
 ('Peter', 'Ferguson', '2004-11-29', '84.33'),
 ('Peter', 'Ferguson', '2004-11-29', '95.30'),
 ('Janine ', 'Labrune', '2004-07-23', '102.04'),
 ('Janine ', 'Labrune', '2004-07-23', '105.94'),
 ('Janine ', 'Labrune', '2004-07-23', '115.37'),
 ('Janine ', 'Labrune', '2004-07-23', '154.93'),
 ('Janine ', 'Labrune', '2004-07-23', '40.15'),
 ('Janine ', 'Labrune', '2004-07-23', '52.09'),
 ('Janine ', 'Labrune', '2004-07-23', '58.00'),
 ('Janine ', 'Labrune', '2004-07-23', '58.47'),
 ('Janine ', 'Labrune', '2004-07-23', '59.96'),
 ('Janine ', 'Labrune', '2004-07-23', '61.70'),
 ('Janine ', 'Labrune', '2004-07-23', '67.38'),
 ('Janine ', 'Labrune', '2004-07-23', '70.12'),
 ('Janine ', 'Labrune', '2004-07-23', '72.00'),
 ('Janine ', 'Labrune', '2004-07-23', '81.35'),
 ('Janine ', 'Labrune', '2004-07-23', '82.77'),
 ('Janine ', 'Labrune', '2004-07-23', '85.86'),
 ('Janine ', 'Labrune', '2004-07-23', '89.90'),
 ('Janine ', 'Labrune', '2004-07-23', '97.38'),
 ('Janine ', 'Labrune', '2004-10-29', '111.83'),
 ('Janine ', 'Labrune', '2004-10-29', '51.32'),
 ('Janine ', 'Labrune', '2004-10-29', '60.67'),
 ('Janine ', 'Labrune', '2004-10-29', '78.12'),
 ('Janine ', 'Labrune', '2004-10-29', '78.77'),
 ('Janine ', 'Labrune', '2004-10-29', '88.39'),
 ('Janine ', 'Labrune', '2004-10-29', '99.17'),
 ('Janine ', 'Labrune', '2005-02-03', '150.62'),
 ('Janine ', 'Labrune', '2005-02-03', '184.84'),
 ('Janine ', 'Labrune', '2005-02-03', '36.22'),
 ('Janine ', 'Labrune', '2005-02-03', '59.85'),
 ('Janine ', 'Labrune', '2005-02-03', '60.13'),
 ('Janine ', 'Labrune', '2005-02-03', '60.26'),
 ('Janine ', 'Labrune', '2005-02-03', '67.03'),
 ('Janine ', 'Labrune', '2005-02-03', '69.16'),
 ('Janine ', 'Labrune', '2005-02-03', '69.60'),
 ('Janine ', 'Labrune', '2005-02-03', '76.56'),
 ('Janine ', 'Labrune', '2005-02-03', '86.77'),
 ('Janine ', 'Labrune', '2005-02-03', '87.90'),
 ('Janine ', 'Labrune', '2005-02-03', '94.73'),
 ('Janine ', 'Labrune', '2005-02-03', '96.95'),
 ('Janine ', 'Labrune', '2005-02-03', '98.48'),
 ('Janine ', 'Labrune', '2005-05-31', '107.76'),
 ('Janine ', 'Labrune', '2005-05-31', '117.82'),
 ('Janine ', 'Labrune', '2005-05-31', '127.79'),
 ('Janine ', 'Labrune', '2005-05-31', '131.49'),
 ('Janine ', 'Labrune', '2005-05-31', '140.55'),
 ('Janine ', 'Labrune', '2005-05-31', '147.36'),
 ('Janine ', 'Labrune', '2005-05-31', '31.82'),
 ('Janine ', 'Labrune', '2005-05-31', '48.62'),
 ('Janine ', 'Labrune', '2005-05-31', '50.32'),
 ('Janine ', 'Labrune', '2005-05-31', '53.75'),
 ('Janine ', 'Labrune', '2005-05-31', '83.79'),
 ('Janine ', 'Labrune', '2005-05-31', '94.92'),
 ('Janine ', 'Labrune', '2005-05-31', '95.99'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '107.34'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '119.67'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '121.64'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '214.30'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '40.75'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '58.34'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '61.84'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '63.35'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '86.31'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '86.92'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '88.62'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '92.19'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '92.46'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '94.07'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '94.50'),
 ('Jonas ', 'Bergulfsen', '2003-01-29', '98.07'),
 ('Jonas ', 'Bergulfsen', '2003-10-10', '67.79'),
 ('Jonas ', 'Bergulfsen', '2004-10-15', '144.60'),
 ('Jonas ', 'Bergulfsen', '2004-10-15', '59.56'),
 ('Jonas ', 'Bergulfsen', '2004-10-15', '74.04'),
 ('Jonas ', 'Bergulfsen', '2004-10-15', '93.89'),
 ('Jonas ', 'Bergulfsen', '2004-10-15', '94.74'),
 ('Jonas ', 'Bergulfsen', '2004-10-15', '96.92'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '111.52'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '114.73'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '114.74'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '166.10'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '193.25'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '44.37'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '55.30'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '56.24'),
 ('Jonas ', 'Bergulfsen', '2004-11-05', '99.55'),
 ('Susan', 'Nelson', '2003-03-26', '101.50'),
 ('Susan', 'Nelson', '2003-03-26', '121.64'),
 ('Susan', 'Nelson', '2003-03-26', '43.27'),
 ('Susan', 'Nelson', '2003-03-26', '58.82'),
 ('Susan', 'Nelson', '2003-07-02', '103.64'),
 ('Susan', 'Nelson', '2003-07-02', '110.39'),
 ('Susan', 'Nelson', '2003-07-02', '133.92'),
 ('Susan', 'Nelson', '2003-07-02', '139.03'),
 ('Susan', 'Nelson', '2003-07-02', '139.64'),
 ('Susan', 'Nelson', '2003-07-02', '173.17'),
 ('Susan', 'Nelson', '2003-07-02', '34.36'),
 ('Susan', 'Nelson', '2003-07-02', '38.62'),
 ('Susan', 'Nelson', '2003-07-02', '49.74'),
 ('Susan', 'Nelson', '2003-07-02', '52.05'),
 ('Susan', 'Nelson', '2003-07-02', '65.94'),
 ('Susan', 'Nelson', '2003-07-02', '66.99'),
 ('Susan', 'Nelson', '2003-07-02', '67.18'),
 ('Susan', 'Nelson', '2003-07-02', '72.62'),
 ('Susan', 'Nelson', '2003-07-02', '76.80'),
 ('Susan', 'Nelson', '2003-07-02', '78.92'),
 ('Susan', 'Nelson', '2003-07-02', '91.85'),
 ('Susan', 'Nelson', '2003-08-08', '114.29'),
 ('Susan', 'Nelson', '2003-08-08', '122.08'),
 ('Susan', 'Nelson', '2003-08-08', '129.76'),
 ('Susan', 'Nelson', '2003-08-08', '140.50'),
 ('Susan', 'Nelson', '2003-08-08', '166.24'),
 ('Susan', 'Nelson', '2003-08-08', '167.83'),
 ('Susan', 'Nelson', '2003-08-08', '46.96'),
 ('Susan', 'Nelson', '2003-08-08', '55.34'),
 ('Susan', 'Nelson', '2003-08-08', '56.24'),
 ('Susan', 'Nelson', '2003-08-08', '60.90'),
 ('Susan', 'Nelson', '2003-08-08', '74.35'),
 ('Susan', 'Nelson', '2003-08-08', '77.08'),
 ('Susan', 'Nelson', '2003-08-08', '79.87'),
 ('Susan', 'Nelson', '2003-08-08', '91.37'),
 ('Susan', 'Nelson', '2003-08-08', '92.16'),
 ('Susan', 'Nelson', '2003-08-08', '95.80'),
 ('Susan', 'Nelson', '2003-11-12', '105.52'),
 ('Susan', 'Nelson', '2003-11-12', '116.27'),
 ('Susan', 'Nelson', '2003-11-12', '135.00'),
 ('Susan', 'Nelson', '2003-11-12', '159.80'),
 ('Susan', 'Nelson', '2003-11-12', '31.86'),
 ('Susan', 'Nelson', '2003-11-12', '34.88'),
 ('Susan', 'Nelson', '2003-11-12', '39.87'),
 ('Susan', 'Nelson', '2003-11-12', '44.21'),
 ('Susan', 'Nelson', '2003-11-12', '54.49'),
 ('Susan', 'Nelson', '2003-11-12', '61.29'),
 ('Susan', 'Nelson', '2003-11-12', '63.20'),
 ('Susan', 'Nelson', '2003-11-12', '73.62'),
 ('Susan', 'Nelson', '2003-11-12', '83.22'),
 ('Susan', 'Nelson', '2003-11-12', '86.31'),
 ('Susan', 'Nelson', '2003-11-12', '87.24'),
 ('Susan', 'Nelson', '2003-11-12', '88.35'),
 ('Susan', 'Nelson', '2003-11-12', '95.30'),
 ('Susan', 'Nelson', '2004-03-11', '104.32'),
 ('Susan', 'Nelson', '2004-03-11', '110.70'),
 ('Susan', 'Nelson', '2004-03-11', '115.01'),
 ('Susan', 'Nelson', '2004-03-11', '119.87'),
 ('Susan', 'Nelson', '2004-03-11', '138.88'),
 ('Susan', 'Nelson', '2004-03-11', '157.49'),
 ('Susan', 'Nelson', '2004-03-11', '34.65'),
 ('Susan', 'Nelson', '2004-03-11', '43.77'),
 ('Susan', 'Nelson', '2004-03-11', '49.78'),
 ('Susan', 'Nelson', '2004-03-11', '52.36'),
 ('Susan', 'Nelson', '2004-03-11', '53.48'),
 ('Susan', 'Nelson', '2004-03-11', '78.97'),
 ('Susan', 'Nelson', '2004-03-11', '91.04'),
 ('Susan', 'Nelson', '2004-03-11', '95.99'),
 ('Susan', 'Nelson', '2004-07-20', '110.00'),
 ('Susan', 'Nelson', '2004-07-20', '121.50'),
 ('Susan', 'Nelson', '2004-07-20', '122.68'),
 ('Susan', 'Nelson', '2004-07-20', '147.36'),
 ('Susan', 'Nelson', '2004-07-20', '169.34'),
 ('Susan', 'Nelson', '2004-07-20', '28.64'),
 ('Susan', 'Nelson', '2004-07-20', '49.71'),
 ('Susan', 'Nelson', '2004-07-20', '51.95'),
 ('Susan', 'Nelson', '2004-07-20', '59.55'),
 ('Susan', 'Nelson', '2004-07-20', '93.76'),
 ('Susan', 'Nelson', '2004-07-20', '99.54'),
 ('Susan', 'Nelson', '2004-08-20', '114.59'),
 ('Susan', 'Nelson', '2004-08-20', '122.93'),
 ('Susan', 'Nelson', '2004-08-20', '132.13'),
 ('Susan', 'Nelson', '2004-08-20', '142.02'),
 ('Susan', 'Nelson', '2004-08-20', '147.36'),
 ('Susan', 'Nelson', '2004-08-20', '169.56'),
 ('Susan', 'Nelson', '2004-08-20', '176.63'),
 ('Susan', 'Nelson', '2004-08-20', '49.71'),
 ('Susan', 'Nelson', '2004-08-20', '51.58'),
 ('Susan', 'Nelson', '2004-08-20', '56.24'),
 ('Susan', 'Nelson', '2004-08-20', '77.95'),
 ('Susan', 'Nelson', '2004-08-20', '88.74'),
 ('Susan', 'Nelson', '2004-08-20', '96.99'),
 ('Susan', 'Nelson', '2004-10-21', '101.50'),
 ('Susan', 'Nelson', '2004-10-21', '102.74'),
 ('Susan', 'Nelson', '2004-10-21', '111.87'),
 ('Susan', 'Nelson', '2004-10-21', '146.20'),
 ('Susan', 'Nelson', '2004-10-21', '150.19'),
 ('Susan', 'Nelson', '2004-10-21', '214.30'),
 ('Susan', 'Nelson', '2004-10-21', '27.88'),
 ('Susan', 'Nelson', '2004-10-21', '40.21'),
 ('Susan', 'Nelson', '2004-10-21', '43.46'),
 ('Susan', 'Nelson', '2004-10-21', '43.67'),
 ('Susan', 'Nelson', '2004-10-21', '44.27'),
 ('Susan', 'Nelson', '2004-10-21', '48.43'),
 ('Susan', 'Nelson', '2004-10-21', '54.34'),
 ('Susan', 'Nelson', '2004-10-21', '84.33'),
 ('Susan', 'Nelson', '2004-10-21', '91.18'),
 ('Susan', 'Nelson', '2004-10-21', '93.20'),
 ('Susan', 'Nelson', '2004-10-21', '96.42'),
 ('Susan', 'Nelson', '2004-11-19', '32.88'),
 ('Susan', 'Nelson', '2004-11-19', '49.78'),
 ('Susan', 'Nelson', '2004-11-19', '77.05'),
 ('Susan', 'Nelson', '2004-12-10', '104.72'),
 ('Susan', 'Nelson', '2004-12-10', '105.34'),
 ('Susan', 'Nelson', '2004-12-10', '109.34'),
 ('Susan', 'Nelson', '2004-12-10', '112.00'),
 ('Susan', 'Nelson', '2004-12-10', '135.92'),
 ('Susan', 'Nelson', '2004-12-10', '199.30'),
 ('Susan', 'Nelson', '2004-12-10', '58.95'),
 ('Susan', 'Nelson', '2004-12-10', '59.34'),
 ('Susan', 'Nelson', '2004-12-10', '84.33'),
 ('Susan', 'Nelson', '2004-12-10', '91.18'),
 ('Susan', 'Nelson', '2005-01-19', '115.09'),
 ('Susan', 'Nelson', '2005-01-19', '36.52'),
 ('Susan', 'Nelson', '2005-01-19', '73.60'),
 ('Susan', 'Nelson', '2005-01-19', '83.04'),
 ('Susan', 'Nelson', '2005-01-19', '93.16'),
 ('Susan', 'Nelson', '2005-01-23', '104.28'),
 ('Susan', 'Nelson', '2005-01-23', '126.51'),
 ('Susan', 'Nelson', '2005-01-23', '160.46'),
 ('Susan', 'Nelson', '2005-01-23', '178.71'),
 ('Susan', 'Nelson', '2005-01-23', '35.01'),
 ('Susan', 'Nelson', '2005-01-23', '44.37'),
 ('Susan', 'Nelson', '2005-01-23', '53.44'),
 ('Susan', 'Nelson', '2005-01-23', '53.75'),
 ('Susan', 'Nelson', '2005-01-23', '82.83'),
 ('Susan', 'Nelson', '2005-01-23', '83.95'),
 ('Susan', 'Nelson', '2005-01-23', '95.81'),
 ('Susan', 'Nelson', '2005-01-23', '97.23'),
 ('Susan', 'Nelson', '2005-02-17', '101.15'),
 ('Susan', 'Nelson', '2005-02-17', '103.10'),
 ('Susan', 'Nelson', '2005-02-17', '115.03'),
 ('Susan', 'Nelson', '2005-02-17', '120.12'),
 ('Susan', 'Nelson', '2005-02-17', '143.61'),
 ('Susan', 'Nelson', '2005-02-17', '145.04'),
 ('Susan', 'Nelson', '2005-02-17', '160.46'),
 ('Susan', 'Nelson', '2005-02-17', '166.24'),
 ('Susan', 'Nelson', '2005-02-17', '46.29'),
 ('Susan', 'Nelson', '2005-02-17', '57.53'),
 ('Susan', 'Nelson', '2005-02-17', '84.33'),
 ('Susan', 'Nelson', '2005-02-17', '85.72'),
 ('Susan', 'Nelson', '2005-02-17', '97.39'),
 ('Susan', 'Nelson', '2005-02-28', '62.00'),
 ('Susan', 'Nelson', '2005-02-28', '78.83'),
 ('Susan', 'Nelson', '2005-03-04', '101.03'),
 ('Susan', 'Nelson', '2005-03-04', '102.98'),
 ('Susan', 'Nelson', '2005-03-04', '117.48'),
 ('Susan', 'Nelson', '2005-03-04', '122.02'),
 ('Susan', 'Nelson', '2005-03-04', '132.29'),
 ('Susan', 'Nelson', '2005-03-04', '134.81'),
 ('Susan', 'Nelson', '2005-03-04', '135.23'),
 ('Susan', 'Nelson', '2005-03-04', '162.00'),
 ('Susan', 'Nelson', '2005-03-04', '35.87'),
 ('Susan', 'Nelson', '2005-03-04', '39.02'),
 ('Susan', 'Nelson', '2005-03-04', '51.43'),
 ('Susan', 'Nelson', '2005-03-04', '54.09'),
 ('Susan', 'Nelson', '2005-03-04', '66.29'),
 ('Susan', 'Nelson', '2005-03-04', '67.87'),
 ('Susan', 'Nelson', '2005-03-04', '75.59'),
 ('Susan', 'Nelson', '2005-03-04', '81.36'),
 ('Susan', 'Nelson', '2005-03-23', '100.77'),
 ('Susan', 'Nelson', '2005-03-23', '129.76'),
 ('Susan', 'Nelson', '2005-03-23', '155.72'),
 ('Susan', 'Nelson', '2005-03-23', '62.00'),
 ('Susan', 'Nelson', '2005-03-23', '77.00'),
 ('Susan', 'Nelson', '2005-03-23', '77.99'),
 ('Susan', 'Nelson', '2005-03-23', '83.38'),
 ('Susan', 'Nelson', '2005-03-23', '91.76'),
 ('Susan', 'Nelson', '2005-05-29', '167.06'),
 ('Susan', 'Nelson', '2005-05-29', '44.80'),
 ('Roland', 'Keitel', '2003-01-09', '108.06'),
 ('Roland', 'Keitel', '2003-01-09', '167.06'),
 ('Roland', 'Keitel', '2003-01-09', '32.53'),
 ('Roland', 'Keitel', '2003-01-09', '44.35'),
 ('Roland', 'Keitel', '2004-03-15', '100.70'),
 ('Roland', 'Keitel', '2004-03-15', '128.42'),
 ('Roland', 'Keitel', '2004-03-15', '142.18'),
 ('Roland', 'Keitel', '2004-03-15', '153.91'),
 ('Roland', 'Keitel', '2004-03-15', '47.40'),
 ('Roland', 'Keitel', '2004-03-15', '57.41'),
 ('Roland', 'Keitel', '2004-03-15', '59.03'),
 ('Roland', 'Keitel', '2004-03-15', '99.36'),
 ('Roland', 'Keitel', '2003-10-04', '116.27'),
 ('Roland', 'Keitel', '2003-10-04', '144.05'),
 ('Roland', 'Keitel', '2003-10-04', '184.84'),
 ('Roland', 'Keitel', '2003-10-04', '52.05'),
 ('Roland', 'Keitel', '2003-10-04', '63.14'),
 ('Roland', 'Keitel', '2003-10-04', '65.94'),
 ('Roland', 'Keitel', '2003-10-04', '76.61'),
 ('Roland', 'Keitel', '2003-10-04', '95.58'),
 ('Roland', 'Keitel', '2004-11-05', '88.30'),
 ('Roland', 'Keitel', '2004-11-05', '96.86'),
 ('Julie', 'Murphy', '2003-03-25', '48.52'),
 ('Julie', 'Murphy', '2003-03-25', '53.09'),
 ('Julie', 'Murphy', '2003-03-25', '85.70'),
 ('Julie', 'Murphy', '2003-03-25', '87.33'),
 ('Julie', 'Murphy', '2003-03-25', '91.27'),
 ('Julie', 'Murphy', '2003-03-25', '94.25'),
 ('Julie', 'Murphy', '2003-12-01', '116.56'),
 ('Julie', 'Murphy', '2003-12-01', '126.52'),
 ('Julie', 'Murphy', '2003-12-01', '191.72'),
 ('Julie', 'Murphy', '2003-12-01', '48.46'),
 ('Julie', 'Murphy', '2003-12-01', '66.27'),
 ('Julie', 'Murphy', '2003-12-01', '82.30'),
 ('Julie', 'Murphy', '2003-12-01', '93.54'),
 ('Julie', 'Murphy', '2004-11-18', '110.84'),
 ('Julie', 'Murphy', '2004-11-18', '121.64'),
 ('Julie', 'Murphy', '2004-11-18', '188.58'),
 ('Julie', 'Murphy', '2004-11-18', '42.26'),
 ('Julie', 'Murphy', '2004-11-18', '62.05'),
 ('Julie', 'Murphy', '2004-11-18', '95.23'),
 ('Julie', 'Murphy', '2004-11-18', '95.24'),
 ('Julie', 'Murphy', '2004-11-18', '95.44'),
 ('Kwai', 'Lee', '2003-02-24', '105.86'),
 ('Kwai', 'Lee', '2003-02-24', '122.00'),
 ('Kwai', 'Lee', '2003-02-24', '172.36'),
 ('Kwai', 'Lee', '2003-02-24', '52.70'),
 ('Kwai', 'Lee', '2003-02-24', '73.12'),
 ('Kwai', 'Lee', '2003-02-24', '81.35'),
 ('Kwai', 'Lee', '2003-02-24', '88.90'),
 ('Kwai', 'Lee', '2003-02-24', '96.92'),
 ('Kwai', 'Lee', '2004-05-07', '122.89'),
 ('Kwai', 'Lee', '2004-05-07', '126.48'),
 ('Kwai', 'Lee', '2004-05-07', '133.86'),
 ('Kwai', 'Lee', '2004-05-07', '53.51'),
 ('Kwai', 'Lee', '2004-05-07', '66.00'),
 ('Kwai', 'Lee', '2004-05-07', '69.39'),
 ('Kwai', 'Lee', '2004-05-07', '80.86'),
 ('Kwai', 'Lee', '2004-05-07', '81.41'),
 ('Kwai', 'Lee', '2004-05-07', '83.02'),
 ('Kwai', 'Lee', '2004-05-07', '84.14'),
 ('Kwai', 'Lee', '2004-05-07', '85.85'),
 ('Kwai', 'Lee', '2004-05-07', '87.77'),
 ('Kwai', 'Lee', '2004-05-07', '92.36'),
 ('Kwai', 'Lee', '2004-05-07', '95.80'),
 ('Kwai', 'Lee', '2004-09-08', '103.09'),
 ('Kwai', 'Lee', '2004-09-08', '113.44'),
 ('Kwai', 'Lee', '2004-09-08', '113.55'),
 ('Kwai', 'Lee', '2004-09-08', '114.90'),
 ('Kwai', 'Lee', '2004-09-08', '140.81'),
 ('Kwai', 'Lee', '2004-09-08', '147.33'),
 ('Kwai', 'Lee', '2004-09-08', '34.30'),
 ('Kwai', 'Lee', '2004-09-08', '48.55'),
 ('Kwai', 'Lee', '2004-09-08', '49.79'),
 ('Kwai', 'Lee', '2004-09-08', '54.11'),
 ('Kwai', 'Lee', '2004-09-08', '59.65'),
 ('Kwai', 'Lee', '2004-09-08', '94.80'),
 ('Kwai', 'Lee', '2004-11-15', '102.49'),
 ('Kwai', 'Lee', '2004-11-15', '104.81'),

## Orders, Order details and Product Details (a Many-to-Many Join)

Return a list of customer first and last names, product names, quantities, and date ordered for each of the customers and each of their orders. Sort these in descending order by the order date.

Note: This will require joining 4 tables! This can be tricky! Give it a shot, and if you're still stuck, turn to the next section where you'll see how to write subqueries which can make complex queries such as this much simpler!

In [8]:
# Your code here
c.execute('''select customers.contactFirstName, customers.contactLastName,
products.productName, orderdetails.quantityOrdered, orders.orderDate 
from customers 
join orders using(customerNumber)
join orderdetails using(orderNumber)
join products using(productCode);''').fetchall()

[('Carine ', 'Schmitt', '1965 Aston Martin DB5', '26', '2003-05-20'),
 ('Carine ', 'Schmitt', '1999 Indy 500 Monte Carlo SS', '46', '2003-05-20'),
 ('Carine ', 'Schmitt', '1948 Porsche Type 356 Roadster', '34', '2003-05-20'),
 ('Carine ', 'Schmitt', '1966 Shelby Cobra 427 S/C', '50', '2003-05-20'),
 ('Carine ', 'Schmitt', '1996 Moto Guzzi 1100i', '39', '2004-09-27'),
 ('Carine ',
  'Schmitt',
  '1936 Harley Davidson El Knucklehead',
  '32',
  '2004-09-27'),
 ('Carine ',
  'Schmitt',
  '1938 Cadillac V-16 Presidential Limousine',
  '43',
  '2004-11-25'),
 ('Jean', 'King', '1917 Grand Touring Sedan', '21', '2003-05-21'),
 ('Jean', 'King', '1911 Ford Town Car', '42', '2003-05-21'),
 ('Jean', 'King', '1932 Model A Ford J-Coupe', '42', '2003-05-21'),
 ('Jean', 'King', '1932 Alfa Romeo 8C2300 Spider Sport', '36', '2003-05-21'),
 ('Jean', 'King', '1957 Ford Thunderbird', '23', '2003-05-21'),
 ('Jean', 'King', '1970 Chevy Chevelle SS 454', '22', '2003-05-21'),
 ('Jean', 'King', '1939 Chevrolet Deluxe Coupe', '45', '2003-05-21'),
 ('Jean',
  'King',
  '1938 Cadillac V-16 Presidential Limousine',
  '22',
  '2003-05-21'),
 ('Jean', 'King', '1949 Jaguar XK 120', '32', '2003-05-21'),
 ('Jean', 'King', '1952 Citroen-15CV', '25', '2003-05-21'),
 ('Jean', 'King', '1969 Chevrolet Camaro Z28', '49', '2003-05-21'),
 ('Jean', 'King', '2002 Chevy Corvette', '43', '2003-05-21'),
 ('Jean', 'King', '1936 Mercedes Benz 500k Roadster', '46', '2003-05-21'),
 ('Jean', 'King', '1993 Mazda RX-7', '34', '2004-08-06'),
 ('Jean', 'King', '1965 Aston Martin DB5', '23', '2004-08-06'),
 ('Jean', 'King', '1948 Porsche 356-A Roadster', '29', '2004-08-06'),
 ('Jean', 'King', '1995 Honda Civic', '29', '2004-08-06'),
 ('Jean', 'King', '1999 Indy 500 Monte Carlo SS', '39', '2004-08-06'),
 ('Jean', 'King', '1992 Ferrari 360 Spider red', '42', '2004-08-06'),
 ('Jean', 'King', '1948 Porsche Type 356 Roadster', '31', '2004-08-06'),
 ('Jean', 'King', '1966 Shelby Cobra 427 S/C', '35', '2004-08-06'),
 ('Jean', 'King', '1982 Lamborghini Diablo', '31', '2004-08-06'),
 ('Jean', 'King', '1956 Porsche 356A Coupe', '25', '2004-08-06'),
 ('Jean', 'King', '1937 Lincoln Berline', '42', '2004-11-29'),
 ('Jean', 'King', '1949 Jaguar XK 120', '25', '2004-11-29'),
 ('Jean', 'King', '1952 Citroen-15CV', '24', '2004-11-29'),
 ('Jean', 'King', '1969 Chevrolet Camaro Z28', '24', '2004-11-29'),
 ('Jean', 'King', '2002 Chevy Corvette', '26', '2004-11-29'),
 ('Jean', 'King', '1936 Mercedes Benz 500k Roadster', '22', '2004-11-29'),
 ('Peter', 'Ferguson', '1996 Moto Guzzi 1100i', '29', '2003-04-29'),
 ('Peter',
  'Ferguson',
  '2003 Harley-Davidson Eagle Drag Bike',
  '46',
  '2003-04-29'),
 ('Peter', 'Ferguson', 'P-51-D Mustang', '29', '2003-04-29'),
 ('Peter',
  'Ferguson',
  '1936 Harley Davidson El Knucklehead',
  '46',
  '2003-04-29'),
 ('Peter', 'Ferguson', '1997 BMW R 1100 S', '35', '2003-04-29'),
 ('Peter', 'Ferguson', '1928 British Royal Navy Airplane', '39', '2003-04-29'),
 ('Peter', 'Ferguson', '1960 BSA Gold Star DBD34', '34', '2003-04-29'),
 ('Peter', 'Ferguson', '1900s Vintage Tri-Plane', '29', '2003-04-29'),
 ('Peter', 'Ferguson', '1997 BMW F650 ST', '22', '2003-04-29'),
 ('Peter', 'Ferguson', '1928 Ford Phaeton Deluxe', '29', '2003-04-29'),
 ('Peter', 'Ferguson', '1930 Buick Marquette Phaeton', '49', '2003-04-29'),
 ('Peter', 'Ferguson', 'American Airlines: B767-300', '47', '2003-04-29'),
 ('Peter', 'Ferguson', 'America West Airlines B757-200', '24', '2003-04-29'),
 ('Peter', 'Ferguson', 'ATA: B757-300', '24', '2003-04-29'),
 ('Peter', 'Ferguson', 'F/A 18 Hornet 1/72', '43', '2003-04-29'),
 ('Peter', 'Ferguson', '1937 Lincoln Berline', '32', '2003-05-21'),
 ('Peter', 'Ferguson', '1928 Mercedes-Benz SSK', '34', '2003-05-21'),
 ('Peter',
  'Ferguson',
  '1969 Harley Davidson Ultimate Chopper',
  '37',
  '2004-02-20'),
 ('Peter', 'Ferguson', '1996 Moto Guzzi 1100i', '47', '2004-02-20'),
 ('Peter',
  'Ferguson',
  '2003 Harley-Davidson Eagle Drag Bike',
  '49',
  '2004-02-20'),
 ('Peter', 'Ferguson', 'P-51-D Mustang', '47', '2004-02-20'),
 ('Peter',
  'Ferguson',
  '1936 Harley Davidson El Knucklehead',
  '28',
  '2004-02-20'),
 ('Peter', 'Ferguson', '1997 BMW R 1100 S', '32', '2004-02-20'),
 ('Peter', 'Ferguson', '1928 British Royal Navy Airplane', '34', '2004-02-20'),
 ('Peter', 'Ferguson', '1960 BSA Gold Star DBD34', '38', '2004-02-20'),
 ('Peter', 'Ferguson', '1900s Vintage Tri-Plane', '23', '2004-02-20'),
 ('Peter', 'Ferguson', '1997 BMW F650 ST', '21', '2004-02-20'),
 ('Peter', 'Ferguson', '1928 Ford Phaeton Deluxe', '20', '2004-02-20'),
 ('Peter', 'Ferguson', '1930 Buick Marquette Phaeton', '41', '2004-02-20'),
 ('Peter', 'Ferguson', 'American Airlines: B767-300', '25', '2004-02-20'),
 ('Peter', 'Ferguson', 'ATA: B757-300', '29', '2004-02-20'),
 ('Peter', 'Ferguson', 'F/A 18 Hornet 1/72', '26', '2004-02-20'),
 ('Peter', 'Ferguson', '1993 Mazda RX-7', '40', '2004-11-24'),
 ('Peter', 'Ferguson', '1948 Porsche 356-A Roadster', '55', '2004-11-24'),
 ('Peter', 'Ferguson', '1995 Honda Civic', '22', '2004-11-24'),
 ('Peter', 'Ferguson', '1992 Ferrari 360 Spider red', '30', '2004-11-24'),
 ('Peter', 'Ferguson', '1969 Dodge Super Bee', '25', '2004-11-24'),
 ('Peter', 'Ferguson', '1976 Ford Gran Torino', '55', '2004-11-24'),
 ('Peter', 'Ferguson', '1957 Vespa GS150', '26', '2004-11-24'),
 ('Peter', 'Ferguson', '1957 Corvette Convertible', '38', '2004-11-24'),
 ('Peter', 'Ferguson', '1982 Lamborghini Diablo', '39', '2004-11-24'),
 ('Peter', 'Ferguson', '1971 Alpine Renault 1600s', '48', '2004-11-24'),
 ('Peter', 'Ferguson', '1956 Porsche 356A Coupe', '42', '2004-11-24'),
 ('Peter', 'Ferguson', '1952 Alpine Renault 1300', '30', '2004-11-29'),
 ('Peter', 'Ferguson', '1962 LanciaA Delta 16V', '27', '2004-11-29'),
 ('Peter', 'Ferguson', '1958 Setra Bus', '29', '2004-11-29'),
 ('Peter', 'Ferguson', '1940 Ford Pickup Truck', '42', '2004-11-29'),
 ('Peter',
  'Ferguson',
  '1936 Mercedes-Benz 500K Special Roadster',
  '21',
  '2004-11-29'),
 ('Peter', 'Ferguson', '1926 Ford Fire Engine', '50', '2004-11-29'),
 ('Peter', 'Ferguson', '1928 Mercedes-Benz SSK', '21', '2004-11-29'),
 ('Peter', 'Ferguson', '1913 Ford Model T Speedster', '48', '2004-11-29'),
 ('Peter', 'Ferguson', '1934 Ford V8 Coupe', '34', '2004-11-29'),
 ('Peter',
  'Ferguson',
  '18th Century Vintage Horse Carriage',
  '45',
  '2004-11-29'),
 ('Peter', 'Ferguson', '1917 Maxwell Touring Car', '26', '2004-11-29'),
 ('Peter', 'Ferguson', '1940s Ford truck', '45', '2004-11-29'),
 ('Janine ',
  'Labrune',
  '1969 Harley Davidson Ultimate Chopper',
  '45',
  '2004-07-23'),
 ('Janine ', 'Labrune', '1996 Moto Guzzi 1100i', '22', '2004-07-23'),
 ('Janine ',
  'Labrune',
  '2003 Harley-Davidson Eagle Drag Bike',
  '36',
  '2004-07-23'),
 ('Janine ', 'Labrune', 'P-51-D Mustang', '35', '2004-07-23'),
 ('Janine ',
  'Labrune',
  '1936 Harley Davidson El Knucklehead',
  '37',
  '2004-07-23'),
 ('Janine ', 'Labrune', '1997 BMW R 1100 S', '21', '2004-07-23'),
 ('Janine ',
  'Labrune',
  '1928 British Royal Navy Airplane',
  '25',
  '2004-07-23'),
 ('Janine ', 'Labrune', '1960 BSA Gold Star DBD34', '30', '2004-07-23'),
 ('Janine ', 'Labrune', 'Corsair F4U ( Bird Cage)', '41', '2004-07-23'),
 ('Janine ', 'Labrune', '1900s Vintage Tri-Plane', '27', '2004-07-23'),
 ('Janine ', 'Labrune', '1997 BMW F650 ST', '23', '2004-07-23'),
 ('Janine ', 'Labrune', '1928 Ford Phaeton Deluxe', '28', '2004-07-23'),
 ('Janine ', 'Labrune', '1930 Buick Marquette Phaeton', '38', '2004-07-23'),
 ('Janine ', 'Labrune', 'American Airlines: B767-300', '32', '2004-07-23'),
 ('Janine ', 'Labrune', 'America West Airlines B757-200', '39', '2004-07-23'),
 ('Janine ', 'Labrune', 'ATA: B757-300', '48', '2004-07-23'),
 ('Janine ', 'Labrune', 'F/A 18 Hornet 1/72', '43', '2004-07-23'),
 ('Janine ', 'Labrune', 'American Airlines: MD-11S', '31', '2004-07-23'),
 ('Janine ', 'Labrune', '1904 Buick Runabout', '36', '2004-10-29'),
 ('Janine ', 'Labrune', '18th century schooner', '35', '2004-10-29'),
 ('Janine ',
  'Labrune',
  '1912 Ford Model T Delivery Wagon',
  '24',
  '2004-10-29'),
 ('Janine ', 'Labrune', 'The Schooner Bluenose', '41', '2004-10-29'),
 ('Janine ', 'Labrune', 'The Titanic', '31', '2004-10-29'),
 ('Janine ', 'Labrune', 'The Queen Mary', '37', '2004-10-29'),
 ('Janine ', 'Labrune', 'Pont Yacht', '40', '2004-10-29'),
 ('Janine ',
  'Labrune',
  '1969 Harley Davidson Ultimate Chopper',
  '21',
  '2005-02-03'),
 ('Janine ', 'Labrune', '1968 Ford Mustang', '45', '2005-02-03'),
 ('Janine ', 'Labrune', '2002 Suzuki XREO', '49', '2005-02-03'),
 ('Janine ', 'Labrune', '1960 BSA Gold Star DBD34', '23', '2005-02-03'),
 ('Janine ', 'Labrune', '1982 Ducati 900 Monster', '20', '2005-02-03'),
 ('Janine ', 'Labrune', '1900s Vintage Tri-Plane', '43', '2005-02-03'),
 ('Janine ', 'Labrune', '1997 BMW F650 ST', '37', '2005-02-03'),
 ('Janine ', 'Labrune', '1928 Ford Phaeton Deluxe', '44', '2005-02-03'),
 ('Janine ', 'Labrune', '1974 Ducati 350 Mk3 Desmo', '41', '2005-02-03'),
 ('Janine ', 'Labrune', '1930 Buick Marquette Phaeton', '49', '2005-02-03'),
 ('Janine ', 'Labrune', '2002 Yamaha YZR M1', '49', '2005-02-03'),
 ('Janine ', 'Labrune', 'American Airlines: B767-300', '37', '2005-02-03'),
 ('Janine ', 'Labrune', 'America West Airlines B757-200', '33', '2005-02-03'),
 ('Janine ', 'Labrune', 'ATA: B757-300', '25', '2005-02-03'),
 ('Janine ', 'Labrune', 'F/A 18 Hornet 1/72', '44', '2005-02-03'),
 ('Janine ', 'Labrune', '1962 LanciaA Delta 16V', '38', '2005-05-31'),
 ('Janine ', 'Labrune', '1957 Chevy Pickup', '33', '2005-05-31'),
 ('Janine ', 'Labrune', '1998 Chrysler Plymouth Prowler', '28', '2005-05-31'),
 ('Janine ', 'Labrune', '1964 Mercedes Tour Bus', '38', '2005-05-31'),
 ('Janine ', 'Labrune', '1926 Ford Fire Engine', '19', '2005-05-31'),
 ('Janine ', 'Labrune', '1992 Ferrari 360 Spider red', '28', '2005-05-31'),
 ('Janine ', 'Labrune', '1940s Ford truck', '38', '2005-05-31'),
 ('Janine ', 'Labrune', '1970 Dodge Coronet', '55', '2005-05-31'),
 ('Janine ', 'Labrune', '1962 Volkswagen Microbus', '49', '2005-05-31'),
 ('Janine ',
  'Labrune',
  '1958 Chevy Corvette Limited Edition',
  '31',
  '2005-05-31'),
 ('Janine ', 'Labrune', '1980’s GM Manhattan Express', '41', '2005-05-31'),
 ('Janine ', 'Labrune', '1954 Greyhound Scenicruiser', '11', '2005-05-31'),
 ('Janine ',
  'Labrune',
  'Diamond T620 Semi-Skirted Tanker',
  '18',
  '2005-05-31'),
 ('Jonas ', 'Bergulfsen', '1952 Alpine Renault 1300', '26', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1962 LanciaA Delta 16V', '42', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1958 Setra Bus', '27', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1940 Ford Pickup Truck', '35', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1926 Ford Fire Engine', '22', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1913 Ford Model T Speedster', '27', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1934 Ford V8 Coupe', '35', '2003-01-29'),
 ('Jonas ',
  'Bergulfsen',
  '18th Century Vintage Horse Carriage',
  '25',
  '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1917 Maxwell Touring Car', '46', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1940s Ford truck', '36', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1939 Cadillac Limousine', '41', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1962 Volkswagen Microbus', '36', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1936 Chrysler Airflow', '25', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1980’s GM Manhattan Express', '31', '2003-01-29'),
 ('Jonas ',
  'Bergulfsen',
  '1996 Peterbilt 379 Stake Bed with Outrigger',
  '45',
  '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1982 Camaro Z28', '42', '2003-01-29'),
 ('Jonas ', 'Bergulfsen', '1960 BSA Gold Star DBD34', '22', '2003-10-10'),
 ('Jonas ',
  'Bergulfsen',
  '1969 Harley Davidson Ultimate Chopper',
  '41',
  '2004-10-15'),
 ('Jonas ', 'Bergulfsen', '2002 Suzuki XREO', '26', '2004-10-15'),
 ('Jonas ', 'Bergulfsen', '1997 BMW R 1100 S', '21', '2004-10-15'),
 ('Jonas ', 'Bergulfsen', '1982 Ducati 900 Monster', '24', '2004-10-15'),
 ('Jonas ', 'Bergulfsen', '1974 Ducati 350 Mk3 Desmo', '50', '2004-10-15'),
 ('Jonas ', 'Bergulfsen', '2002 Yamaha YZR M1', '28', '2004-10-15'),
 ('Jonas ', 'Bergulfsen', '1972 Alfa Romeo GTA', '47', '2004-11-05'),
 ('Jonas ', 'Bergulfsen', '2001 Ferrari Enzo', '42', '2004-11-05'),
 ('Jonas ', 'Bergulfsen', '1969 Ford Falcon', '24', '2004-11-05'),
 ('Jonas ', 'Bergulfsen', '1903 Ford Model A', '24', '2004-11-05'),
 ('Jonas ',
  'Bergulfsen',
  '1992 Porsche Cayenne Turbo Silver',
  '44',
  '2004-11-05'),
 ('Jonas ', 'Bergulfsen', '1954 Greyhound Scenicruiser', '38', '2004-11-05'),
 ('Jonas ',
  'Bergulfsen',
  "1950's Chicago Surface Lines Streetcar",
  '28',
  '2004-11-05'),
 ('Jonas ',
  'Bergulfsen',
  'Diamond T620 Semi-Skirted Tanker',
  '38',
  '2004-11-05'),
 ('Jonas ',
  'Bergulfsen',
  '1962 City of Detroit Streetcar',
  '44',
  '2004-11-05'),
 ('Susan', 'Nelson', '1958 Setra Bus', '21', '2003-03-26'),
 ('Susan', 'Nelson', '1940 Ford Pickup Truck', '49', '2003-03-26'),
 ('Susan', 'Nelson', '1939 Cadillac Limousine', '50', '2003-03-26'),
 ('Susan',
  'Nelson',
  '1996 Peterbilt 379 Stake Bed with Outrigger',
  '23',
  '2003-03-26'),
 ('Susan', 'Nelson', '1968 Ford Mustang', '42', '2003-07-02'),
 ('Susan', 'Nelson', '1968 Dodge Charger', '48', '2003-07-02'),
 ('Susan', 'Nelson', '1970 Plymouth Hemi Cuda', '24', '2003-07-02'),
 ('Susan', 'Nelson', '1969 Dodge Charger', '29', '2003-07-02'),
 ('Susan', 'Nelson', '1948 Porsche 356-A Roadster', '48', '2003-07-02'),
 ('Susan', 'Nelson', '1969 Dodge Super Bee', '45', '2003-07-02'),
 ('Susan', 'Nelson', '1976 Ford Gran Torino', '42', '2003-07-02'),
 ('Susan', 'Nelson', '1957 Vespa GS150', '45', '2003-07-02'),
 ('Susan', 'Nelson', '1957 Corvette Convertible', '31', '2003-07-02'),
 ('Susan', 'Nelson', '1982 Ducati 900 Monster', '29', '2003-07-02'),
 ('Susan', 'Nelson', '1982 Lamborghini Diablo', '20', '2003-07-02'),
 ('Susan', 'Nelson', '1971 Alpine Renault 1600s', '27', '2003-07-02'),
 ('Susan', 'Nelson', '1956 Porsche 356A Coupe', '47', '2003-07-02'),
 ('Susan', 'Nelson', '1961 Chevrolet Impala', '23', '2003-07-02'),
 ('Susan', 'Nelson', '1982 Ducati 996 R', '33', '2003-07-02'),
 ('Susan', 'Nelson', '1974 Ducati 350 Mk3 Desmo', '30', '2003-07-02'),
 ('Susan', 'Nelson', '2002 Yamaha YZR M1', '44', '2003-07-02'),
 ('Susan', 'Nelson', '2001 Ferrari Enzo', '33', '2003-08-08'),
 ('Susan', 'Nelson', '1969 Corvair Monza', '33', '2003-08-08'),
 ('Susan', 'Nelson', '1969 Ford Falcon', '46', '2003-08-08'),
 ('Susan', 'Nelson', '1903 Ford Model A', '47', '2003-08-08'),
 ('Susan', 'Nelson', 'Collectable Wooden Train', '22', '2003-08-08'),
 ('Susan', 'Nelson', '1970 Triumph Spitfire', '24', '2003-08-08'),
 ('Susan', 'Nelson', '1904 Buick Runabout', '24', '2003-08-08'),
 ('Susan', 'Nelson', '18th century schooner', '33', '2003-08-08'),
 ('Susan', 'Nelson', '1912 Ford Model T Delivery Wagon', '49', '2003-08-08'),
 ('Susan',
  'Nelson',
  "1950's Chicago Surface Lines Streetcar",
  '42',
  '2003-08-08'),
 ('Susan', 'Nelson', '1962 City of Detroit Streetcar', '42', '2003-08-08'),
 ('Susan', 'Nelson', 'The Schooner Bluenose', '41', '2003-08-08'),
 ('Susan', 'Nelson', 'The Mayflower', '43', '2003-08-08'),
 ('Susan', 'Nelson', 'The Titanic', '21', '2003-08-08'),
 ('Susan', 'Nelson', 'The Queen Mary', '38', '2003-08-08'),
 ('Susan', 'Nelson', 'Pont Yacht', '39', '2003-08-08'),
 ('Susan', 'Nelson', '1937 Lincoln Berline', '25', '2003-11-12'),
 ('Susan',
  'Nelson',
  '1936 Mercedes-Benz 500K Special Roadster',
  '32',
  '2003-11-12'),
 ('Susan', 'Nelson', '1917 Grand Touring Sedan', '44', '2003-11-12'),
 ('Susan', 'Nelson', '1911 Ford Town Car', '38', '2003-11-12'),
 ('Susan', 'Nelson', '1932 Model A Ford J-Coupe', '20', '2003-11-12'),
 ('Susan', 'Nelson', '1928 Mercedes-Benz SSK', '21', '2003-11-12'),
 ('Susan', 'Nelson', '1917 Maxwell Touring Car', '33', '2003-11-12'),
 ('Susan',
  'Nelson',
  '1932 Alfa Romeo 8C2300 Spider Sport',
  '36',
  '2003-11-12'),
 ('Susan', 'Nelson', '1957 Ford Thunderbird', '44', '2003-11-12'),
 ('Susan', 'Nelson', '1970 Chevy Chevelle SS 454', '47', '2003-11-12'),
 ('Susan', 'Nelson', '1939 Chevrolet Deluxe Coupe', '39', '2003-11-12'),
 ('Susan',
  'Nelson',
  '1938 Cadillac V-16 Presidential Limousine',
  '31',
  '2003-11-12'),
 ('Susan', 'Nelson', '1949 Jaguar XK 120', '36', '2003-11-12'),
 ('Susan', 'Nelson', '1952 Citroen-15CV', '20', '2003-11-12'),
 ('Susan', 'Nelson', '1969 Chevrolet Camaro Z28', '33', '2003-11-12'),
 ('Susan', 'Nelson', '2002 Chevy Corvette', '49', '2003-11-12'),
 ('Susan', 'Nelson', '1936 Mercedes Benz 500k Roadster', '23', '2003-11-12'),
 ('Susan', 'Nelson', '1962 LanciaA Delta 16V', '50', '2004-03-11'),
 ('Susan', 'Nelson', '1958 Setra Bus', '25', '2004-03-11'),
 ('Susan', 'Nelson', '1957 Chevy Pickup', '36', '2004-03-11'),
 ('Susan', 'Nelson', '1964 Mercedes Tour Bus', '26', '2004-03-11'),
 ('Susan', 'Nelson', '1926 Ford Fire Engine', '28', '2004-03-11'),
 ('Susan', 'Nelson', '1992 Ferrari 360 Spider red', '22', '2004-03-11'),
 ('Susan', 'Nelson', '1940s Ford truck', '41', '2004-03-11'),
 ('Susan', 'Nelson', '1939 Cadillac Limousine', '39', '2004-03-11'),
 ('Susan', 'Nelson', '1962 Volkswagen Microbus', '48', '2004-03-11'),
 ('Susan',
  'Nelson',
  '1958 Chevy Corvette Limited Edition',
  '33',
  '2004-03-11'),
 ('Susan', 'Nelson', '1980’s GM Manhattan Express', '25', '2004-03-11'),
 ('Susan', 'Nelson', '1954 Greyhound Scenicruiser', '23', '2004-03-11'),
 ('Susan',
  'Nelson',
  '1996 Peterbilt 379 Stake Bed with Outrigger',
  '30',
  '2004-03-11'),
 ('Susan', 'Nelson', '1982 Camaro Z28', '50', '2004-03-11'),
 ('Susan', 'Nelson', '1957 Chevy Pickup', '31', '2004-07-20'),
 ('Susan', 'Nelson', '1998 Chrysler Plymouth Prowler', '50', '2004-07-20'),
 ('Susan', 'Nelson', '1964 Mercedes Tour Bus', '50', '2004-07-20'),
 ('Susan', 'Nelson', '1926 Ford Fire Engine', '25', '2004-07-20'),
 ('Susan', 'Nelson', '1992 Ferrari 360 Spider red', '20', '2004-07-20'),
 ('Susan', 'Nelson', '1970 Dodge Coronet', '45', '2004-07-20'),
 ('Susan', 'Nelson', '1962 Volkswagen Microbus', '43', '2004-07-20'),
 ('Susan',
  'Nelson',
  '1958 Chevy Corvette Limited Edition',
  '38',
  '2004-07-20'),
 ('Susan', 'Nelson', '1992 Porsche Cayenne Turbo Silver', '22', '2004-07-20'),
 ('Susan', 'Nelson', '1954 Greyhound Scenicruiser', '35', '2004-07-20'),
 ('Susan', 'Nelson', 'Diamond T620 Semi-Skirted Tanker', '34', '2004-07-20'),
 ('Susan', 'Nelson', '2001 Ferrari Enzo', '41', '2004-08-20'),
 ('Susan', 'Nelson', '1969 Corvair Monza', '27', '2004-08-20'),
 ('Susan', 'Nelson', '1969 Ford Falcon', '24', '2004-08-20'),
 ('Susan', 'Nelson', '1998 Chrysler Plymouth Prowler', '23', '2004-08-20'),
 ('Susan', 'Nelson', '1903 Ford Model A', '43', '2004-08-20'),
 ('Susan', 'Nelson', 'Collectable Wooden Train', '36', '2004-08-20'),
 ('Susan', 'Nelson', '1970 Triumph Spitfire', '31', '2004-08-20'),
 ('Susan', 'Nelson', '1970 Dodge Coronet', '29', '2004-08-20'),
 ('Susan', 'Nelson', '1992 Porsche Cayenne Turbo Silver', '39', '2004-08-20'),
 ('Susan',
  'Nelson',
  "1950's Chicago Surface Lines Streetcar",
  '36',
  '2004-08-20'),
 ('Susan', 'Nelson', 'Diamond T620 Semi-Skirted Tanker', '38', '2004-08-20'),
 ('Susan', 'Nelson', '1962 City of Detroit Streetcar', '37', '2004-08-20'),
 ('Susan', 'Nelson', 'The Mayflower', '43', '2004-08-20'),
 ('Susan', 'Nelson', '1952 Alpine Renault 1300', '48', '2004-10-21'),
 ('Susan', 'Nelson', '1940 Ford Pickup Truck', '32', '2004-10-21'),
 ('Susan', 'Nelson', '1937 Lincoln Berline', '43', '2004-10-21'),
 ('Susan',
  'Nelson',
  '1936 Mercedes-Benz 500K Special Roadster',
  '25',
  '2004-10-21'),
 ('Susan', 'Nelson', '1917 Grand Touring Sedan', '48', '2004-10-21'),
 ('Susan', 'Nelson', '1911 Ford Town Car', '30', '2004-10-21'),
 ('Susan', 'Nelson', '1932 Model A Ford J-Coupe', '31', '2004-10-21'),
 ('Susan', 'Nelson', '1928 Mercedes-Benz SSK', '25', '2004-10-21'),
 ('Susan', 'Nelson', '1913 Ford Model T Speedster', '37', '2004-10-21'),
 ('Susan', 'Nelson', '1934 Ford V8 Coupe', '35', '2004-10-21'),

## Summary

In this lab, you practiced your knowledge on one-to-many and many-to-many relationships!